function noError(number){
let x = 5;
if(number == x){
console.log("great");
}else{
console.log("Try again")
}
}

